"""  completed

Revision ID: 29fdebe1a971
Revises: ad75ba5df62a
Create Date: 2023-07-31 22:36:31.397314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fdebe1a971'
down_revision = 'ad75ba5df62a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
