"""add columns completed

Revision ID: 42f2d577bce5
Revises: da7f8024bba9
Create Date: 2023-07-30 17:08:23.279173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f2d577bce5'
down_revision = 'da7f8024bba9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
