"""  completed_1

Revision ID: 86f48ca44c26
Revises: c73663e779af
Create Date: 2023-07-31 22:39:52.799046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f48ca44c26'
down_revision = 'c73663e779af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
