"""up2  completed

Revision ID: b7dda38239e5
Revises: 3630b2579b7f
Create Date: 2023-07-31 21:13:34.912799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7dda38239e5'
down_revision = '3630b2579b7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
