"""Init

Revision ID: da7f8024bba9
Revises: 22dca89eef86
Create Date: 2023-07-30 16:06:49.304033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da7f8024bba9'
down_revision = '22dca89eef86'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
