"""  completed_2

Revision ID: ea80a4bf747a
Revises: 86f48ca44c26
Create Date: 2023-07-31 22:41:14.496243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea80a4bf747a'
down_revision = '86f48ca44c26'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
